### ISSUE TITLE
mouse pressed is mouse released and vice versa

### ISSUE THREAD

**Issue by ChristianRathke** [kristian/system-hook#1]
In GlobalMouseHook.java "mousePressed" is called after the mouse has gone up and "mouseReleased" is called after the mouse has gone down...

**Comment by kristian** [comment]
What a bug. Fixed with 8d1ab72708f237692867c2fa1d52a841e5c8a74d and version [2.3](/kristian/system-hook/releases/tag/2.3). Thank you!
