### ISSUE TITLE
Support for determining keyboard used?

### ISSUE THREAD

**Issue by 28andrew** [kristian/system-hook#12]
I wonder if it is possible to add support for determining the keyboard being used. Maybe return the unique keyboard "id".

**Comment by kristian** [comment]
Good idea. I think that'd fit the library really well. Unfortunately I don't think the LowLevel routines provided by Windows do provide such a "keyboard id". Input it input, regardless of which device the input came from. If somebody has an idea, please feel ree to comment. I'll let this issue stay open for reference.

**Comment by 28andrew** [comment]
Interception does it somehow. I think it uses a driver. LuaMacros also does it, I don't think it uses a driver.
Both of these aren't in Java but maybe you can do something similar with JNI.
https://github.com/oblitum/Interception
https://github.com/me2d13/luamacros

**Comment by 28andrew** [comment]
Oops sorry, closed it by accident.

**Comment by kristian** [comment]
Nice, I'll take a look at it as soon as I find some spare time.

**Comment by kristian** [comment]
Hello Andrew, good news. With the next major revision of this library, I decided switching from the Windows "Hook Functions" to the newer "[Raw Input](https://msdn.microsoft.com/library/windows/desktop/ms645543.aspx)" API. This will essentially drop support for Windows 2000 machines, whilst bringing a lot of advantages along:

- The raw input API is newer and better documented by Microsoft
- It's even "lower" level, than the Hook Functions used so far, which I think fits this library very well
- It removes some "wonky" debris of the old implementation (e.g. dead key handling)
- And, last but not least, it adds the possibility of determining on which input device the key was pressed!

I'll use this issue to keep you updated about the progress. Hope this helps.

**Comment by 28andrew** [comment]
Wow, that's amazing. I didn't expect you to still consider supporting it months later. I'm looking forward on the progress. 😄

**Comment by mwss1996** [comment]
This will be a great improvement. Could we expect a release date?

**Comment by kristian** [comment]
Hello Michael, if everything goes as planned maybe already this Sunday. For the third major release I am planning to do some major changes to the library:

- Moving from the "Hook Functions" to the "Raw Input" API
- Merging the Mouse/Keyboard Hook Native Libraries, which should effectively cut the library size in half
- ~~Add basic "posting" support for keys / mouse events (see #10)~~

**Comment by mwss1996** [comment]
Wow, i was thinking this wanna take months.
It's possible to get the devices names too? I was thinking in let the user to choose the proper device to get the input.

**Comment by kristian** [comment]
No promises, but I'll try to add that as well.

**Comment by kristian** [comment]
Done. Released version 3.0. Enjoy!
