### ISSUE TITLE
All global key presses have the same device handle

### ISSUE THREAD

**Issue by 28andrew** [kristian/system-hook#16]
With the code
```java
GlobalKeyboardHook globalKeyboardHook = new GlobalKeyboardHook();

        globalKeyboardHook.addKeyListener(new GlobalKeyAdapter(){
            @Override
            public void keyPressed(GlobalKeyEvent event) {
                System.out.println(event.getVirtualKeyCode());
                System.out.println("Keyboard: " + event.getDeviceHandle());
            }
        });
```
It gives me a device handle of `0` even though I have 2 Logitech keyboards plugged in (one wireless, one wired). I restarted the application to try again and it still persisted.
![image](https://user-images.githubusercontent.com/9660418/27011963-bddaaf3a-4e8c-11e7-881b-4c48e283dcf9.png)
![image](https://user-images.githubusercontent.com/9660418/27011970-e5e7026c-4e8c-11e7-92d0-06ae39312a4b.png)
![image](https://user-images.githubusercontent.com/9660418/27011980-005ac692-4e8d-11e7-91df-fbc13a9bdbb4.png)

**Comment by 28andrew** [comment]
Looking at code this may be hardcoded?
https://github.com/kristian/system-hook/blob/master/src/main/native/windows/SystemHook.c#L110
```c
handleKey("LowLevelKeyboardProc", wParam, pStruct->vkCode, pStruct->scanCode, 0);
```
The 0 is passed onto ▽
https://github.com/kristian/system-hook/blob/master/src/main/native/windows/SystemHook.c#L82
```c
static void handleKey(const char *nProc, UINT event, USHORT vkCode, USHORT scanCode, HANDLE hDevice) {
```
▽
https://github.com/kristian/system-hook/blob/master/src/main/native/windows/SystemHook.c#L101
```c
(*env)->CallVoidMethod(env, hookObj[HOOK_KEYBOARD], handleMeth[HOOK_KEYBOARD], vkCode, tState, (jchar)buffer[0], (jlong)(uintptr_t)hDevice);
```

Though I'm not a C programmer.

**Comment by 28andrew** [comment]
Both keyboards show up in GlobalKeyboardHook#getKeyBords (not a typo on my side)

```
ID: 240453973
Name: \\?\HID#VID_04CA&PID_0027&MI_00#8&ed03796&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}
ID: 209717173
Name: \\?\HID#VID_046D&PID_C517&MI_00#8&3d273a5&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}
```

**Comment by kristian** [comment]
You will have to initialize the GlobalKeyBoardHook with the parameter true `new GlobalKeyboardHook(true)`, to enable the new "raw input" mode. If `false` is passed, you are still using the old keyboard hook (for legacy compliance reasons). As soon as you "switch on" raw mode, you should get the device ID.

Thanks for noticing the typo. I'll fix it and re-upload a 3.1 build. Thanks.

**Comment by kristian** [comment]
Fixed with 3.1.

**Comment by 28andrew** [comment]
Kind of ironic how there is a typo in the commit message 😆

**Comment by kristian** [comment]
Well at least I wanted to highlight the severity of minor version 3.1 ;)
