### ISSUE TITLE
System hook fails.

### ISSUE THREAD

**Issue by JayVem** [kristian/system-hook#2]
The sample code on the main page fails with the following error, 

`Exception in thread "Global Keyboard Hook Thread" Global keyboard hook successfully started, press [escape] key to shutdown.
java.lang.UnsatisfiedLinkError: lc.kra.system.keyboard.GlobalKeyboardHook$NativeKeyboardHook.registerHook()I
    at lc.kra.system.keyboard.GlobalKeyboardHook$NativeKeyboardHook.registerHook(Native Method)
    at lc.kra.system.keyboard.GlobalKeyboardHook$NativeKeyboardHook.run(GlobalKeyboardHook.java:174)`
I copied 32 bit keyboard and mousehook .dll files to C:\windows\system32, which is on the java.library.path. The machine I am running has 32bit windows 7.

**Comment by slessard** [comment]
There should be no need to extract the DLLs from the jar file as the native DLLs should be able to directly from the jar file.  Debugging the LibraryLoader class should make it quite clear exactly what file name the code is trying to load. Have you tried stepping through LibraryLoader code?

**Comment by kristian** [comment]
@slessard is right, the `LibraryLoader` class is used to locate the native library files. Using the JAR package should be sufficient, as all needed DLL files are already included. If you would like to put the DLL files into your `java.library.path` or the systems `PATH` instead, please debug the first two lines of the `LibraryLoader` class. The `System.loadLibrary(libName);` command is used to load the libraries. Just check the `libName` variable, to find out how your files have to be named.

**Comment by Ahmed8485** [comment]
I am also still getting this error.
I am on windows 7 professional

> LibraryLoader.class
> libName: keyboardhook-windows-x86.dll
> tempFile: C:\Users\III\AppData\Local\Temp\keyboardhook-6612558809975635852.dll

Error is thrown while calling 

> keyboardHook = new NativeKeyboardHook()

If I try forcefully loading the 64bit dll. It says 

> Can't load AMD 64-bit .dll on a IA 32-bit platform

**Comment by kristian** [comment]
@Ahmed8485, please make sure you are using the right JRE for your platform. Are you using 32-bit or 64-bit Windows 7 Professional? Could you please paste the exception stack trace? Also please go to the command line and paste the result of `java -version`.

**Comment by Ahmed8485** [comment]
Thanks for the reply.
Windows 7 64 bit
java 64 bit
`C:\Users\ADMIN>java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)`

Heres the error
`Exception in thread "Global Keyboard Hook Thread" java.lang.UnsatisfiedLinkError: lc.kra.system.keyboard.GlobalKeyboardHook$NativeKeyboardHook.registerHook()I
    at lc.kra.system.keyboard.GlobalKeyboardHook$NativeKeyboardHook.registerHook(Native Method)
    at lc.kra.system.keyboard.GlobalKeyboardHook$NativeKeyboardHook.run(GlobalKeyboardHook.java:174)
Global keyboard hook successfully started, press [escape] key to shutdown.
`

**Comment by kristian** [comment]
@Ahmed8485 are you using the bundled JAR file provided, or are you using the class files as is and try to load the DLL files elsewhere? If so, as suggested for JayVem, please try to debug `LibraryLoader` to see, which DLL file is chosen (32-bit or 64-bit) and which one is load.

**Comment by mohamed0123** [comment]
I know this answer too late for you , but may help other.
go to the project https://github.com/kristian/system-hook/releases
then download the system-hook-3.1.jar then extract the content of jar using 7zip,winrar any decompress application 
and in your extraction folder go to \lc\kra\system\lib folder ten copy the content of this folder 
to the project at /system-hook/src/main/java/lc/kra/system/lib path and it will work with you
