### ISSUE TITLE
Where to get libsystemhook-linux-amd64.so?

### ISSUE THREAD

**Issue by TheNotary** [kristian/system-hook#20]
Hello, I'm consuming this project on a linux machine just to [test things out](https://github.com/thenotary/inputanalysis), and I get this message:

```
$ ./target/InputAnalysis 
Hello World!
Exception in thread "main" java.lang.UnsatisfiedLinkError: lib: libsystemhook-linux-amd64.so not found in lib directory
	at lc.kra.system.LibraryLoader.loadLibrary(LibraryLoader.java:86)
	at lc.kra.system.keyboard.GlobalKeyboardHook.<init>(GlobalKeyboardHook.java:98)
	at my_app_group.App.listenToInputs(App.java:44)
	at my_app_group.App.main(App.java:37)
```

There's a comment indicating this might happen, but I'm a little confused as to how to overcome it.  Should I do an `apt-get install` to get it on my machine?  Googling brings me [here](https://github.com/bgroenks96/java-global-input-hook) to a github page by someone else where the library seems to be available.  Are those files safe and is that repo the only way to produce the files?

**Comment by TheNotary** [comment]
As an update, I running my exact code more or less works fine on windows machines, it's just not working on my Linux Mint machine.

**Comment by kristian** [comment]
Linux support has not been added to this library. Nice that you found a library already implementing the native dependencies on Linux. I will take a look at them and come back to this. Unfortuantely I cannot give you any ETA when Linux support is officially added to this Library, as I am kind of busy doing other things right now.

**Comment by pwitiw** [comment]
Hello,
I would also like to use this library for Linux.  Is ETA still unknown?

**Comment by kristian** [comment]
Hello Patryk, yes... unfortunately. If nobody will provide me with a pull-request to accept, I do currently find no time to do the Linux port of the native libraries myself. Sorry for that.

**Comment by abcdw** [comment]
@TheNotary https://github.com/kwhat/jnativehook probably works on Linux and covers same features.

**Comment by kristian** [comment]
Linux support likely will never be provided, see #49. Happy to accept any PRs! Closing with "wont-fix" for now, sorry.
