### ISSUE TITLE
Press key during a specific delay

### ISSUE THREAD

**Issue by Safraann** [kristian/system-hook#22]
Hello there, first great work for this library, this is just awesome. I implemented it in a custom steering wheel for omsi 2 with a potentiometer. The system is pretty easy, when pot has 45 percents value on his axe, i calculate the equivalent in omsi wheel turns. But i need to be the most accurate as possible. When i turn 8 percent on my pot, it has to make an entiere turn in the game, so with my keyboard, the equivalent would be the holding Num4 pad key pressing during 1 sec, how can i fake that delay feature with your lib ? I tried to sleep the thread between press and release functions but i doesn't do something of interesting. Thanks you in advance !

**Comment by kristian** [comment]
Hello Jules. To be honest, I am not entirely sure what you are trying to achieve. The library does currently not feature to simulate key presses. So I am not entirely sure, what you'd like to time? Currently the library only features to record key presses. The events are timed, as they are received by the keyboard itself. Also I am a little unsure what should be provided from a library point of view here. Thanks.

**Comment by Safraann** [comment]
Thanks for your quick answer and really sorry kristian, i confused your library with Java'sone, here is my code:
https://pastebin.com/iV7GeU8R

Have you any idea to improve that code in the goal to maintain active the press during few seconds ?

**Comment by kristian** [comment]
Hello Junes, sorry. I cannot provide you with any guidance on how to accurcately deal with the AWT Robot implementation. You might have to ask on Stackoverflow or so.
