### ISSUE TITLE
GlobalKeyboardHook does not work on windows when TaskManager is in focus

### ISSUE THREAD

**Issue by LogicBig** [kristian/system-hook#28]
I tried GlobalKeyboardExample it works fine but does not work when a system dialog e.g. TaskManager or
Registry Editor (regex) is in focus. Looks like those dialogs consume all events. Is that possible to create a keyboard hook to listen at lower level?

**Comment by kristian** [comment]
To the best of my knowlege this is a security mechanism introduced by Windows, in order for you to not do any malicious activities on those system critical apps. SystemHook already utilizes two very low level APIs (`SetWindowsHookEx` and if the `raw` flag is set it creates an invisible message-only window). But as the name suggests, these are both APIs which are provided to you by the operating system. So if the operating system is preventing you from reading certain inputs, there is no way arround that.

**Comment by amiru3f** [comment]
Hi Dude, hope this is not too late to post!
Just run your keylogger (or app that enabled hook) as Administrator,
hook chain on elevated apps UI will just be passed to elevated key loggers.
