### ISSUE TITLE
UnsatisfiedLinkError when using system hook in WebStart

### ISSUE THREAD

**Issue by ChristianRathke** [kristian/system-hook#3]
When I try to use system-hook in a WebStart situation (https://www.hdm-stuttgart.de/~rathke/Trader/GlobalMouse.jnlp)  I get the following error:

```
JNLPClassLoader: Finding library mousehook.dll
Exception in thread "Global Mouse Hook Thread" java.lang.UnsatisfiedLinkError: lc.kra.system.mouse.GlobalMouseHook$NativeMouseHook.registerHook()I
    at lc.kra.system.mouse.GlobalMouseHook$NativeMouseHook.registerHook(Native Method)
    at lc.kra.system.mouse.GlobalMouseHook$NativeMouseHook.run(GlobalMouseHook.java:196)
Global mouse hook successfully started, press [middle] mouse button to shutdown.
```

The native library seems to load ok but when trying to register a hook the error occurs. Note that this does not happen when running the exact same code locally as in

`java -jar system-hook.jar lc.kra.system.mouse.example.GlobalMouseExample 
`

**Comment by kristian** [comment]
For WebStart applications I guess you'll have to use the `<nativelib>` tag, to specify native library files. It's not enough to just include them in the bundled JAR. See the [JNLP File Syntax](http://docs.oracle.com/javase/7/docs/technotes/guides/javaws/developersguide/syntax.html) documentation.

Try to downlaod the DLL files from [Appvoyer](https://ci.appveyor.com/project/kristian/system-hook), put them in a JAR archive and specify multiple `<resource>` directives in your JNLP file, like so:

```
<!-- Windows 64-bit native libraries -->
<resources os="Windows" arch="amd64">
    <nativelib href="system-hook-amd64.jar"/>
</resources>
    <resources os="Windows" arch="x86_64">
<nativelib href="system-hook-amd64.jar"/>
</resources>
<!-- Windows 32-bit native libraries -->
<resources os="Windows" arch="x86">
    <nativelib href="system-hook-x86.jar"/>
</resources>
<resources os="Windows" arch="i386">
    <nativelib href="system-hook-x86.jar"/>
</resources>
```

_Note:_ I never actually tried this. If the library is not found still, try to debug through the `LibraryLoader` class. Hope this helps. Maybe we have to adapt the class to work with WebStart.

**Comment by ChristianRathke** [comment]
I identified the problem: when using WebStart the 32-bit-version of Java was used for the launcher instead of the 64-bit-version. Accessing the 64-bit-library file caused the problem. Just deinstalling the 32-bit jre from my system solved the issue.
Sorry for the bother.

**Comment by kristian** [comment]
@ChristianRathke did you have to specify the library files with `<nativelib>`, or was it fine to use the bundled JAR? Glad it worked in the end.

**Comment by ChristianRathke** [comment]
It was fine just with the bundled JAR. Although I might try your suggested option as a lot of mousehook-????.dll files accumulate in the temp directory over time. For some reason deleting the library file after loading it does not work - neither locally nor when using WebStart.

**Comment by kristian** [comment]
> For some reason deleting the library file after loading it does not work

This sounds bad. Generally the files should clean up after they've been loaded. Could you please open another issue on that one? Thanks!
