### ISSUE TITLE
just for windows OS ?

### ISSUE THREAD

**Issue by ljheee** [kristian/system-hook#33]
can i use it in linux 、Mac？

**Comment by markozajc** [comment]
As far as I know, that isn't possible (at least not with the provided natives)

**Comment by luecking** [comment]
There are alternatives. 
Please check https://github.com/dstjacques/JHotKeys, it is a wrapper for JIntellitype (Windows) and JXGrabKey (Linux).
Keep in mind, that the behavior could be in detail different to system-hook!

**Comment by kristian** [comment]
Hello ljheee, luecking and markozajc are right, JSysHook currently ONLY supports Windows! There are already issues addressing this (#20, #27), but currently I don't find any time to drive the impelemtnation personally. In case you'd like to take that, please feel free to raise a pull request. I will close this issue as a duplicate to the two linked issues. Thanks.
