### ISSUE TITLE
maven central

### ISSUE THREAD

**Issue by jjYBdx4IL** [kristian/system-hook#36]
Please add it to maven central. There is currently no other such library there.

**Comment by luecking** [comment]
There are other similar libraries, like JIntellitype. 
But keep in mind, that they have differences in detail!

In general I like it, if you have alternatives, so I agree to put system-hook also to maven-central.

**Comment by jjYBdx4IL** [comment]
well, I recently discovered that all of the functionality is already present in jna-platform. One just has to look at two examples there.
