### ISSUE TITLE
forwarded key events vs. blocked key events

### ISSUE THREAD

**Issue by luecking** [kristian/system-hook#37]
Hello,
I've following situation. 
I currently use JIntellitype which doesn't forward captured key events.
With system-hook I recognized, that key events are forwarded to following possible listeners.

Both has pros and cons. Is there a possibility to make it configurable?

Means, if I set the HotKey I could also set the param if the HotKey will be captured only by my application or stays alive and can be captured by other applications.

Could be a nice new feature.

**Comment by kristian** [comment]
Hello @luecking, I think this is a good idea. I just checked the documentation to confirm calling `CallNextHookEx` is indeed *optional*. But please be aware: Whether you get or not get the events, depends on the order of hooks registered. It could be that another application registered the hook, which will lead to your hook NOT beeing triggered and vice versa. I will see what I can do.

**Comment by kristian** [comment]
Done with #fc7691603677c28cc0bcf7a8f6c8307058bc9985 and release 3.5
