### ISSUE TITLE
Hook seems to not work in games

### ISSUE THREAD

**Issue by Codenarski** [kristian/system-hook#42]
Hi, 
i wanted to use your hook to spam a single button. The spam works inside a notepad file, the browser and any other application i tested, but not inside the game i want to use it. Game runs in Windowmode.

**Comment by kristian** [comment]
Hello Jan, likely the game uses a different Windows API in order to capture it's keystrokes. Also this library is for listening to keystrokes, not for sending them. So you likely are not using this library to send the keystrokes but a different one.
