### ISSUE TITLE
Multiple Keys

### ISSUE THREAD

**Issue by JaCoB123456798** [kristian/system-hook#43]
There seems to be detection issues when using multiple keys at once sometimes. This doesn't happen with the mouse because there is a way to manually check each key instead of relying on the single key returned by the event's function.

**Comment by luecking** [comment]
Hello, 
I recognized this also when using the windows hook in a different way.
I think it was like (CTRL-ALT-A): You can press CTRL-ALT first and then A, but not the other way around. Sometimes I also recognized this between CTRL and ALT.
