### ISSUE TITLE
lib: systemhook-windows-amd64.dll not found in lib directory

### ISSUE THREAD

**Issue by Zzerr0r** [kristian/system-hook#50]
just cloned the project and tried to run GlobalKeyboardExample. Seems some /lib folder is missing

**Comment by Hellosager** [comment]
There is currently no support for other OS besides Windows.

Refer to:
https://github.com/kristian/system-hook/issues/33#issuecomment-508064153

**Comment by Zzerr0r** [comment]
I am on Windows

**Comment by Hellosager** [comment]
My bad... it's in the title. I thought it's the same as #49

**Comment by kristian** [comment]
Sorry for the late reply. The repository does not contain any (pre-build) DLLs, meaning you will have to either build them locally on your PC, or download them from appveyor and put them into the /libs folder, in order to run the library locally.
