### ISSUE TITLE
how could i make it so it locks the mouse input?

### ISSUE THREAD

**Issue by Sadcrysbro** [kristian/system-hook#53]

**Comment by kristian** [comment]
I am bound by the windows APIs used in the native implementation. Generally the hook is free to not continue propagating the event to any hooks that registered afterwards, however, it depends on when the hook that you wan to "block" the mouse input for registered, or if they are utilizing any other kind of (even more lower level) API to access the mouse events. Please have a look at the native mouse hook implementation, the code for it is pretty straight forward. You can try registering the hook in "FINAL" mode, see the comment in the following file: https://github.com/kristian/system-hook/blob/master/src/main/java/lc/kra/system/GlobalHookMode.java#L8C1-L11C8. Hope this helps.
