### ISSUE TITLE
Events not firing

### ISSUE THREAD

**Issue by fidelcom1** [kristian/system-hook#9]
Hello! I using the next code, but events are never firing :(
My code:
https://code.re/jBvNhc79

What I doing wrong? In my log:

NATIVE: DllMain - DLL_PROCESS_ATTACH
Hook Created!
Thread Working!
Thread Working!
Thread Working!
Thread Working!
...

Thank you!

**Comment by kristian** [comment]
Hello! :-) Can you please download the debug build of the library from [AppVeyor](https://ci.appveyor.com/project/kristian/system-hook), try again and paste the console output please? Thanks.

**Comment by kristian** [comment]
I'm closing this, as I havn't heared back the problem likely is already resolved.
